theme: jekyll-theme-hacker
title:  Welcome to the Gitithere's homepage!  Made By Odeon with real pieces of panther!  Works 60% of the time - Everytime!
description:  Feel free to bookmark this to keep an eye on my project updates
